### ISSUE TITLE
Value beginning with '-' causes error

### ISSUE THREAD

**Issue by bluec** [Zookal/HarrisStreet-ImpEx#8]
Example YAML:

    some_settings/setting/config_value:
      default:
        0: '-15px'

Trying to import the above results in the following error:

    [RuntimeException]               
      The "-1" option does not exist.  

Seems to be the same for any value starting with a minus sign.

**Comment by SchumacherFM** [comment]
I think this is caused by the n98 core functions ...

**Comment by bluec** [comment]
Yes I just had the same realisation.

**Comment by bluec** [comment]
In case anyone else comes across this it was fixed by the change in #12
